### ISSUE TITLE
Game stops allowing me to do anything when it is my turn

### ISSUE THREAD

**Issue by aarowhead** [cs340tabyu/cs340Fall2017#325] opened 2017-11-23 05:53 UTC
A little ways into the game the game will say it is my turn but won't let me do anything. When I do an action the toast say it as if it worked but then it doesn't update any deck number or anything.

**Comment by drmercer** [comment] 2017-11-27 19:19
@conman124 I wonder if this is related to the issue we saw, where the turn indicator didn't update. Could also be an issue with the poller being stuck.

**Comment by conman124** [comment] 2017-11-27 19:25
Yeah, my guess is the indicator maybe didn't update, making it seem like it
was still aarowhead's turn when it actually wasn't.

**Comment by drmercer** [comment] 2017-11-28 23:18
Could not reproduce. Closing.

**Closed as completed by drmercer** 2017-11-28 23:18 UTC
Labels: P2: Halts Gameplay, Could Not Reproduce, Team 7
