### ISSUE TITLE
3

### ISSUE THREAD

**Issue by ryandday** [cs340tabyu/cs340Fall2017#135] opened 2017-11-21 19:41 UTC
Some decks show negative numbers, cards don't reset, game has hard time functioning

**Comment by scottcrossen** [comment] 2017-11-24 05:53
what do you mean "cards don't reset". and "game has hard time functioning". Could you be more specific? Also, the negative numbers issue is a duplicate of https://github.com/cs340tabyu/cs340Fall2017/issues/154 (unless you found that the destination card deck also showed negative numbers which would be helpful to know).

**Comment by scottcrossen** [comment] 2017-11-25 09:10
I've rigorously tested the zero-card base case. Unless further information is provided, this issue is resolved.

**Closed as completed by scottcrossen** 2017-11-25 09:10 UTC
Labels: Team Seth
