### ISSUE TITLE
Both players can be in draw dest card dialog at the same time

### ISSUE THREAD

**Issue by wunter8** [cs340tabyu/cs340Fall2017#293] opened 2017-11-22 08:00 UTC

**Comment by dylanmrowe** [comment] 2017-11-27 07:15
This was intended. They each receive a completely separate set of cards.

**Comment by dylanmrowe** [comment] 2017-11-27 09:13
If we really need to fix this, I'll fix it.

**Comment by dylanmrowe** [comment] 2017-11-27 20:26
This is similar to game flow in real-life games - at the beginning of the game, all players can draw destination cards around the same time, and all be discarding at the same time. This is what our implementation allows. Closing for now. (The only potential problem is when we run our of destination cards, but that's super rare.)

**Closed as completed by dylanmrowe** 2017-11-27 20:26 UTC
Labels: P1: Severe, Arthur and Friends
